### ISSUE TITLE
Genview on Hugging Face

### ISSUE THREAD

**Issue by merveenoyan** [xiaojieli0903/genview#1]
Hello @xiaojieli0903  🤗

I'm Merve and I work on computer vision at Hugging Face. I see your paper is accepted as ECCV Posters congratulations! I indexed it here https://huggingface.co/papers/2403.12003 at paper pages. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.

I see you're going to release the models. Would you like to host the model you've pre-trained with this technique on https://huggingface.co/models?  Hosting on Hugging Face will give your work more visibility.

If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.
You can also build a demo to your model on [Spaces](https://huggingface.co/spaces) we can provide you an A100 grant.

What do you think?

**Comment by xiaojieli0903** [comment]
> Hello @xiaojieli0903 🤗
> 
> I'm Merve and I work on computer vision at Hugging Face. I see your paper is accepted as ECCV Posters congratulations! I indexed it here https://huggingface.co/papers/2403.12003 at paper pages. The paper page lets people discuss about your paper and lets them find artifacts about it (your model for instance) you can also claim the paper as yours which will show up on your public profile at HF.
> 
> I see you're going to release the models. Would you like to host the model you've pre-trained with this technique on https://huggingface.co/models? Hosting on Hugging Face will give your work more visibility.
> 
> If you're down, leaving a guide [here](https://huggingface.co/docs/hub/models-uploading). If it's a PyTorch model, you can use [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class which adds from_pretrained and push_to_hub to the model which lets you to upload the model and people to download and use models right away. If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).
> 
> After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model. You can also build a demo to your model on [Spaces](https://huggingface.co/spaces) we can provide you an A100 grant.
> 
> What do you think?

Hello Merve,

Thank you for reaching out and for indexing our paper on Hugging Face. We would be happy to upload our pre-trained models and the generated training set to Hugging Face for the community to use and test. We plan to release these models around the time of the ECCV conference.

Thank you for your guidance, and if we have any further questions, we'll be sure to contact you promptly.

Best regards,
Xiaojie Li

**Comment by merveenoyan** [comment]
@xiaojieli0903 thanks a lot for the response! feel free to ask questions (also I'm at ECCV, will try to find your session :)

**Comment by xiaojieli0903** [comment]
Hi Merve @merveenoyan ,
Thank you so much for your help and patience! I’ve uploaded the pre-trained models to https://huggingface.co/Xiaojie0903/genview_pretrained_models and linked them to the paper page. Apologies for the delay due to other commitments. I’ll continue uploading the dataset to Hugging Face soon.

Best regards,
Xiaojie
